// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcky1DwY6RoBovDn-o9XKv2d5rI7Xz_WM',
    appId: '1:846477852289:web:2e8c106a508dbd7e565780',
    messagingSenderId: '846477852289',
    projectId: 'piracyguard',
    authDomain: 'piracyguard.firebaseapp.com',
    storageBucket: 'piracyguard.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM3sKgXuZ0vCrECz3GxgL622_6Bia8pSs',
    appId: '1:846477852289:android:95da636601f45da7565780',
    messagingSenderId: '846477852289',
    projectId: 'piracyguard',
    storageBucket: 'piracyguard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgXduBiNcEH1DLCWQjjfWTKbcUGzahVlo',
    appId: '1:846477852289:ios:ee0c2dc06e4306a0565780',
    messagingSenderId: '846477852289',
    projectId: 'piracyguard',
    storageBucket: 'piracyguard.firebasestorage.app',
    androidClientId: '846477852289-lutqobnb41c8oofu4f8l027s05o1j8vp.apps.googleusercontent.com',
    iosClientId: '846477852289-bjc4dhjrnqtlcto8ik0g789nib1fs9uj.apps.googleusercontent.com',
    iosBundleId: 'com.example.piracyguard',
  );
}
